
const $=(e,t=document)=>t.querySelector(e),$$_=(e,t=document)=>Array.from(t.querySelectorAll(e));
function initCountdown(){const e=document.getElementById("countdown");if(!e)return;const t=localStorage.getItem("surpriseDateISO");let n=t||e.dataset.target||"";const o=document.getElementById("surprise-datetime"),c=document.getElementById("save-surprise");if(o){if(n){const e=new Date(n),t=e=>String(e).padStart(2,"0"),c=`${e.getFullYear()}-${t(e.getMonth()+1)}-${t(e.getDate())}T${t(e.getHours())}:${t(e.getMinutes())}`;o.value=c}c&&c.addEventListener("click",(()=>{if(!o.value)return;const e=new Date(o.value).toISOString();localStorage.setItem("surpriseDateISO",e),n=e}))}const a=document.getElementById("cd-days"),d=document.getElementById("cd-hours"),l=document.getElementById("cd-mins"),r=document.getElementById("cd-secs");function i(){if(!n)return a.textContent="0",d.textContent="0",l.textContent="0",void(r.textContent="0");const e=new Date,t=new Date(n),o=t.getTime()-e.getTime();if(o<=0)return a.textContent="0",d.textContent="0",l.textContent="0",void(r.textContent="0");const c=Math.floor(o/1e3),i=Math.floor(c/86400),s=Math.floor(c%86400/3600),u=Math.floor(c%3600/60),m=c%60;a.textContent=String(i),d.textContent=String(s),l.textContent=String(u),r.textContent=String(m)}i(),setInterval(i,1e3)}
async function loadPhotosFromJSON(){try{const e=await fetch("assets/photos/photos.json",{cache:"no-store"});if(!e.ok)return[];const t=await e.json();return Array.isArray(t)?t.filter(Boolean).map((e=>({src:String(e.src||e),alt:e.alt?String(e.alt):"Ricordo"}))):[]}catch{return[]}}
function buildCarousel(e){const t=document.getElementById("carousel-track");t&&(t.innerHTML="",e.forEach((e=>{const n=document.createElement("img");n.loading="lazy",n.decoding="async",n.src=e.src,n.alt=e.alt||"Ricordo",t.appendChild(n)})))}
function bindCarouselControls(){const e=document.getElementById("carousel-track"),t=document.querySelector(".carousel__btn.prev"),n=document.querySelector(".carousel__btn.next");if(!e||!t||!n)return;const o=()=>e.clientWidth;t.addEventListener("click",(()=>e.scrollBy({left:-o(),behavior:"smooth"}))),n.addEventListener("click",(()=>e.scrollBy({left:o(),behavior:"smooth"})));let c=setInterval((()=>e.scrollBy({left:o(),behavior:"smooth"})),5e3);e.addEventListener("mouseenter",(()=>clearInterval(c))),e.addEventListener("mouseleave",(()=>c=setInterval((()=>e.scrollBy({left:o(),behavior:"smooth"})),5e3)));let a=0;e.addEventListener("touchstart",(e=>{a=e.touches[0].clientX}),{passive:!0}),e.addEventListener("touchend",(e=>{const o=e.changedTouches[0].clientX-a;Math.abs(o)>40&&(o>0?t.click():n.click())}))}
function enableLocalUploads(e){const t=document.getElementById("photo-input");t&&t.addEventListener("change",(()=>{const n=t.files;if(!n||!n.length)return;const o=Array.from(n).map((e=>new Promise((t=>{const n=new FileReader;n.onload=(()=>t({src:String(n.result),alt:e.name}))),n.readAsDataURL(e)}))));Promise.all(o).then((t=>{buildCarousel([...e,...t])}))}))}
async function loadTimeline(){try{const e=await fetch("assets/timeline.json",{cache:"no-store"});if(!e.ok)return[];const t=await e.json();return Array.isArray(t)?t:[]}catch{return[]}}
function renderTimeline(e){const t=document.getElementById("timeline");if(!t)return;t.innerHTML="",e.sort(((e,t)=>e.date.localeCompare(t.date)));for(const n of e){const e=document.createElement("li"),o=document.createElement("div");o.className="timeline__dot",e.appendChild(o);const c=document.createElement("div");c.className="timeline__card",e.appendChild(c);const a=document.createElement("div");a.className="timeline__date",a.textContent=new Date(n.date).toLocaleDateString("it-IT",{year:"numeric",month:"long",day:"numeric"});const d=document.createElement("div");d.className="timeline__title",d.textContent=n.title;const l=document.createElement("p");l.className="timeline__desc",l.textContent=n.description||"",c.append(a,d,l),t.appendChild(e)}}
function spawnFloating(){const e=document.querySelector(".floating--hearts"),t=document.querySelector(".floating--flowers");if(!e||!t)return;const n=window.innerWidth,o=window.innerHeight,c=(e,t)=>Math.random()*(t-e)+e;for(let t=0;t<18;t++){const t=document.createElement("div");t.className="heart",t.style.left=c(0,n-20)+"px",t.style.bottom=c(-40,40)+"px",t.style.animation=`floatUp ${c(14,26)}s linear ${c(0,12)}s infinite, drift ${c(6,12)}s ease-in-out ${c(0,8)}s infinite alternate`,e.appendChild(t)}for(let e=0;e<26;e++){const e=document.createElement("div");e.className="flower",e.style.left=c(0,n-20)+"px",e.style.bottom=c(-40,40)+"px",e.style.animation=`floatUp ${c(18,30)}s linear ${c(0,14)}s infinite, drift ${c(5,10)}s ease-in-out ${c(0,8)}s infinite alternate`,t.appendChild(e)}}
(async function(){initCountdown();const e=await loadPhotosFromJSON();buildCarousel(e),bindCarouselControls(),enableLocalUploads(e);const t=await loadTimeline();renderTimeline(t),spawnFloating()})();
